services:
  api1:
    image: ghcr.io/steixeira93/rinha-backend-26-v2-api:sha-fbb4214cbccbed0d48b16540c864036eb036455a@sha256:3ae3656b39ffad7d2edb8d779bfd8d9b8c8b15449af5ac0cfcdf8b3981bec021
    command: ["/sockets/api1.sock", "/index/index.bin", "1"]
    volumes:
      - sockets:/sockets
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"

  api2:
    image: ghcr.io/steixeira93/rinha-backend-26-v2-api:sha-fbb4214cbccbed0d48b16540c864036eb036455a@sha256:3ae3656b39ffad7d2edb8d779bfd8d9b8c8b15449af5ac0cfcdf8b3981bec021
    command: ["/sockets/api2.sock", "/index/index.bin", "1"]
    volumes:
      - sockets:/sockets
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"

  lb:
    image: jrblatt/so-no-forevis:v0.0.2
    restart: always
    environment:
      - UPSTREAMS=/sockets/api1.sock,/sockets/api2.sock
      - PORT=9999
      - BUF_SIZE=4096
      - WORKERS=1
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30M"

volumes:
  sockets:
