services:
  api1:
    image: ghcr.io/steixeira93/rinha-backend-26-v2-api:latest
    command: ["/sockets/api1.sock", "/index/index.bin"]
    volumes:
      - sockets:/sockets
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160M"

  api2:
    image: ghcr.io/steixeira93/rinha-backend-26-v2-api:latest
    command: ["/sockets/api2.sock", "/index/index.bin"]
    volumes:
      - sockets:/sockets
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160M"

  lb:
    image: ghcr.io/steixeira93/rinha-backend-26-v2-lb:latest
    command: ["0.0.0.0:9999", "/sockets/api1.sock", "/sockets/api2.sock"]
    volumes:
      - sockets:/sockets:ro
    ports:
      - "9999:9999"
    depends_on: [api1, api2]
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30M"

volumes:
  sockets:
