services:
  api1:
    image: ghcr.io/steixeira93/rinha-backend-26-v2-api:sha-b2a0e190eba7e032b43e5bf710873dd5bc9d9f77
    command: ["/sockets/api1.sock", "/index/index.bin", "1"]
    volumes:
      - sockets:/sockets
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

  api2:
    image: ghcr.io/steixeira93/rinha-backend-26-v2-api:sha-b2a0e190eba7e032b43e5bf710873dd5bc9d9f77
    command: ["/sockets/api2.sock", "/index/index.bin", "1"]
    volumes:
      - sockets:/sockets
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

  lb:
    image: ghcr.io/steixeira93/rinha-backend-26-v2-lb:sha-b2a0e190eba7e032b43e5bf710873dd5bc9d9f77
    command: ["0.0.0.0:9999", "/sockets/api1.sock", "/sockets/api2.sock"]
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets:ro
    depends_on: [api1, api2]
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"

volumes:
  sockets:
