services:
  api1:
    image: ${NATIVE_IMAGE:-ghcr.io/d3vk1ng1337/rinha-backend-26-v2-native:sha-ca8d5dc4b5506e31b9156eb4d2ea50467dac6421@sha256:ef6c5ed79b284539d872eb7e7a6c0f540d7dd273517ebe69913b235c763ac4b9}
    platform: linux/amd64
    command: ["server"]
    environment:
      LISTEN: /sockets/api1.sock
      INDEX_PATH: /index/index.bin
      NPROBE: "${NPROBE:-12}"
      FAST_NPROBE: "${FAST_NPROBE:-0}"
      ADAPTIVE_MIN: "${ADAPTIVE_MIN:-2}"
      ADAPTIVE_MAX: "${ADAPTIVE_MAX:-4}"
      EXTREME0_WORST_THRESHOLD: "${EXTREME0_WORST_THRESHOLD:-3501932}"
      EXTREME1_WORST_THRESHOLD: "${EXTREME1_WORST_THRESHOLD:-3569273}"
      EXTREME2_WORST_THRESHOLD: "${EXTREME2_WORST_THRESHOLD:-2906420}"
      EXTREME3_WORST_THRESHOLD: "${EXTREME3_WORST_THRESHOLD:-2738652}"
      EXTREME4_WORST_THRESHOLD: "${EXTREME4_WORST_THRESHOLD:-3297753}"
      EXTREME5_WORST_THRESHOLD: "${EXTREME5_WORST_THRESHOLD:-4594089}"
      REPAIR_MIN: "${REPAIR_MIN:-0}"
      REPAIR_MAX: "${REPAIR_MAX:-5}"
      INDEX_MMAP: "1"
      MALLOC_ARENA_MAX: "1"
    volumes:
      - sockets:/sockets

  api2:
    image: ${NATIVE_IMAGE:-ghcr.io/d3vk1ng1337/rinha-backend-26-v2-native:sha-ca8d5dc4b5506e31b9156eb4d2ea50467dac6421@sha256:ef6c5ed79b284539d872eb7e7a6c0f540d7dd273517ebe69913b235c763ac4b9}
    platform: linux/amd64
    command: ["server"]
    environment:
      LISTEN: /sockets/api2.sock
      INDEX_PATH: /index/index.bin
      NPROBE: "${NPROBE:-12}"
      FAST_NPROBE: "${FAST_NPROBE:-0}"
      ADAPTIVE_MIN: "${ADAPTIVE_MIN:-2}"
      ADAPTIVE_MAX: "${ADAPTIVE_MAX:-4}"
      EXTREME0_WORST_THRESHOLD: "${EXTREME0_WORST_THRESHOLD:-3501932}"
      EXTREME1_WORST_THRESHOLD: "${EXTREME1_WORST_THRESHOLD:-3569273}"
      EXTREME2_WORST_THRESHOLD: "${EXTREME2_WORST_THRESHOLD:-2906420}"
      EXTREME3_WORST_THRESHOLD: "${EXTREME3_WORST_THRESHOLD:-2738652}"
      EXTREME4_WORST_THRESHOLD: "${EXTREME4_WORST_THRESHOLD:-3297753}"
      EXTREME5_WORST_THRESHOLD: "${EXTREME5_WORST_THRESHOLD:-4594089}"
      REPAIR_MIN: "${REPAIR_MIN:-0}"
      REPAIR_MAX: "${REPAIR_MAX:-5}"
      INDEX_MMAP: "1"
      MALLOC_ARENA_MAX: "1"
    volumes:
      - sockets:/sockets

  lb:
    image: haproxy:2.9-alpine
    ports:
      - "3457:9999"
    volumes:
      - sockets:/sockets:ro
      - ./haproxy-gate.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2

volumes:
  sockets:
